# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 19:04
from __future__ import unicode_literals

from django.db import migrations
import csv


def add_players(apps, schema_editor):
    Player = apps.get_model("first_app", "Player")
    with open("playerinfo.csv") as playerinfo:
        info = csv.DictReader(playerinfo)
        for row in info:
            Player.objects.create(name=row["name"], age=row["age"], number=row["number"], position=row["position"],
                                  goals=row["goals"], assists=row["assists"], saves=row["saves"], team=row["team"])
            # print (row)

    # raise Exception("BOOMSHAKALAKA!")


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_players)
    ]
